### ISSUE TITLE
Error appears after sending message 

### ISSUE THREAD

**Issue by damian398** [Taewan-P/gpt_mobile#110]
**Describe the bug**
Error appears after sending reply to any of chatgpt bots. 

Error: Fields [id, created, model, choices] are required for type with serial name 'com.aallam.openai.api.chat.ChatCompletionChunk', but they were missing at path: $

**Screenshots or Screen Recording**
screenshot attached

**Additional context**
FYI, I'm using openrouter.ai account and have the API URL and API key inputed and every went ok until that error message appear. i try to click retry but the error message reappear again. strangely after so many attempts to click the retry button, sometime the message sent successfully (get a reply from the chatbot/success). 
i don't know what the problem is, but my account is working perfectly at other app.
![IMG_20241106_090948](https://github.com/user-attachments/assets/ca480678-6c46-4d60-9b6f-e1e8542f6ce5)

**Comment by Taewan-P** [comment]
Hi Thanks for the report! I will look into it. There may be compatibility issues of the openai format that OpenAI support.

**Comment by damian398** [comment]
Hi, i want to update the progress, everything goes well right now. thank you for your time and hardwork for this app.
