### ISSUE TITLE
Bug reporr

### ISSUE THREAD

**Issue by daniela2000111** [Taewan-P/gpt_mobile#115]
It looks like you’re drafting a bug report template. Here’s a refined version to ensure clarity and completeness:

---

Bug Description
Provide a clear and concise description of the bug.

---

Steps to Reproduce
List the steps to reproduce the bug:

2. Click on '...'

3. Scroll down to '...'

4. Observe the error

---

Expected Behavior
Describe what you expected to happen instead of the observed issue.

---

Screenshots or Screen Recordings
If relevant, attach any screenshots or screen recordings that illustrate the problem.

---

Environment Details

Device/OS (e.g., Windows, macOS, Android, iOS):

Browser/Version (if applicable):

App Version (if applicable):

Other relevant details:

---

Additional Context
Provide any other information that might be useful, like recent changes to the environment or relevant error logs.

---

Feel free to customize it further to suit your project’s needs!

**Comment by Taewan-P** [comment]
Please enter details about the issue. I will close this for now.
