### ISSUE TITLE
Error when using Together AI via the OpenAI configuration settings.

### ISSUE THREAD

**Issue by clc-github** [Taewan-P/gpt_mobile#116]
**Describe the bug**
When configured to use Together AI (https://api.together.xyz/v1/)  via the OpenAI configuration settings, querys result in an index out of bounds error.

**To Reproduce**

1. Open the OpenAI Settings
2. Set the API URL to https://api.together.xyz/v1/
3. Set the API Key to a Together AI API key.
4. Set the API Model to meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo
5. Start a new chat
6. Ask "who is donald duck?" in the chat.
7. Wait for the response to stream back, clear, then be replaced with an error message.

**Expected behavior**
1. The streamed response would remain on the screen rather than being cleared.
2. No error message.

**Screenshots or Screen Recording**
I forgot to take one before I replaced the APK on my phone with a patched version.

**Additional context**
I originally installed the application using F-Droid.

Here is a quick patch I used to build a debug APK that seems to work.  I've only run a couple of tests so far but they were successful.

```
--- a/app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt
+++ b/app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt
@@ -64,11 +64,28 @@ class ChatRepositoryImpl @Inject constructor(
             topP = platform.topP?.toDouble()
         )
 
+//        return openAI.chatCompletions(chatCompletionRequest)
+//            .map<ChatCompletionChunk, ApiState> { chunk -> ApiState.Success(chunk.choices[0].delta?.content ?: "") }
+//            .catch { throwable -> emit(ApiState.Error(throwable.message ?: "Unknown error")) }
+//            .onStart { emit(ApiState.Loading) }
+//            .onCompletion { emit(ApiState.Done) }
+
         return openAI.chatCompletions(chatCompletionRequest)
-            .map<ChatCompletionChunk, ApiState> { chunk -> ApiState.Success(chunk.choices[0].delta?.content ?: "") }
+            .map<ChatCompletionChunk, ApiState> { chunk ->
+                when {
+                    // isEmpty is hit with together.ai
+                    // is this really ApiState.Done?
+                    chunk.choices.isEmpty() -> ApiState.Done
+                    //chunk.choices.isEmpty() -> ApiState.Error("No choices received")
+                    chunk.choices[0].delta == null -> ApiState.Error("Delta is null")
+                    chunk.choices[0].delta?.content == null -> ApiState.Error("Content is null")
+                    else -> ApiState.Success(chunk.choices[0].delta?.content ?: "")
+                }
+            }
             .catch { throwable -> emit(ApiState.Error(throwable.message ?: "Unknown error")) }
             .onStart { emit(ApiState.Loading) }
             .onCompletion { emit(ApiState.Done) }
+
     }
```

**Comment by Taewan-P** [comment]
@clc-github Hi. Thanks for the report.

This is occurred due to the misimplemented OpenAI compatibility of Together AI. This issue actually should be reported to TogetherAI team.

Main reason of the error is the streamed chunk choices' list. The last chunk choice list is empty, but OpenAI API never returns this empty. Interestingly, I tried with another model in TogetherAI, but there were no issues with it.

However, this bug should be handled in the client side as well, so I will include this fix in the next update.
