### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by ThatOneCalculator** [Taewan-P/gpt_mobile#18]
Support for self-hosted Ollama servers would be great

**Comment by Taewan-P** [comment]
Do they have a unified output format? Any API references?

**Comment by ThatOneCalculator** [comment]
https://github.com/ollama/ollama/blob/main/docs%2Fapi.md

**Comment by randoentity** [comment]
Wouldn't it make more sense to just use the openai api spec? That adds support for many inference servers, including ollama (didn't they also just use the openai api spec?).

**Comment by Taewan-P** [comment]
@randoentity Wow, after seeing your comment I tried searching for that... and surprisingly it is ([link](https://ollama.com/blog/openai-compatibility))
This will make it more easy to implement the feature. Thanks! 😃

**Comment by ThatOneCalculator** [comment]
I would recommend against using the OpenAI API layer, as it's still WIP and missing many features.

**Comment by Taewan-P** [comment]
There is not really much feature we need rn. If chat completion works, I think that's good for now.

**Comment by ThatOneCalculator** [comment]
Ok, the chat completion works so as long as remote models can be listed with the regular Ollama API, I don't see an issue. It would be nice to have vision/etc in the future though
