### ISSUE TITLE
Add an option to set API URL

### ISSUE THREAD

**Issue by Integral-Tech** [Taewan-P/gpt_mobile#19]
It would be better if an option to set API URL is provided.

**Comment by Taewan-P** [comment]
Is there a reason that this feature is needed?

**Comment by Integral-Tech** [comment]
> Is there a reason that this feature is needed?

There are some third-party GPT proxy services such as [AiHubMix](https://aihubmix.com) which doesn't use the official OpenAI domain (https://openai.com).

**Comment by suhan-paradkar** [comment]
This link lists out such proxy instances... 
https://github.com/LiLittleCat/awesome-free-chatgpt/blob/main/README_en.md
