### ISSUE TITLE
Skip platform selection when one platform is active

### ISSUE THREAD

**Issue by PanderMusubi** [Taewan-P/gpt_mobile#22]
Skip the following dialog to select a platform when only one platform has an API key and is active. This will reduce the number of GUI actions a usre has to do.

![Screenshot_20240719-071411_GPTMobile_1](https://github.com/user-attachments/assets/69eb3e5c-38f8-4fcd-a5d7-540e732975d4)

**Comment by Taewan-P** [comment]
Nice point. Thanks
