### ISSUE TITLE
[Feature Request]Support for custom API endpoint and model name

### ISSUE THREAD

**Issue by Lucas04-nhr** [Taewan-P/gpt_mobile#40]
I wonder if the app can add a feature to let thr user to set their own 3rd-party API endpoint (such as https://example.com/v1/completions) and custom model name (such as gpt-3.5-turbo-0125).

**Comment by Taewan-P** [comment]
3rd party API endpoint support will be included in the next release. (See #33)
We don't support custom model name yet.

**Comment by Lucas04-nhr** [comment]
Thanks!

**Comment by Lucas04-nhr** [comment]
> We don't

May I ask if you'd planned to add the support of custom model name?

**Comment by Taewan-P** [comment]
Resolved at #47.
