### ISSUE TITLE
Bug: Flickering and misplacement of text selection and context menu in input field

### ISSUE THREAD

**Issue by vonhyd** [Taewan-P/gpt_mobile#46]
## Description
   When selecting text in the input field of the application, the selected text flickers and shifts undesirably. Additionally, the context menu does not stay aligned with the selection and moves outside the input box when the user scrolls while selecting text.

   ## Steps to Reproduce  
   1. Open the app and navigate to the input field where text can be entered.
   2. Begin selecting text by holding and dragging the selection handles.
   3. Observe the text selection flickering and jumping around.
   4. While text is selected, attempt to scroll through the input field.
   5. Notice the context menu shifts position and moves outside the input box.

   ## Expected Behavior  
   - Text selection should remain stable and not flicker or move unexpectedly.
   - The context menu should stay aligned with the selected text, even when scrolling.

   ## Actual Behavior  
   - Text selection flickers and moves unpredictably when selecting.
   - The context menu misaligns and appears outside the input box upon scrolling.

   ## Environment  
   - Device: Pixel 7
   - OS: Android 14 (Graphene OS Build 2024092900)
   - App Version: v0.4.1

   ## Additional Information  
![IMG_20241003_093557](https://github.com/user-attachments/assets/8a2c408a-b1dd-49ec-a278-764a328aa18d)
![ezgif-6-370e65f4b9](https://github.com/user-attachments/assets/d8481129-0e07-4f75-9509-cb83482282a4)

**Comment by Taewan-P** [comment]
Thanks for the report, I'll be fixing it as soon as possible.

**Comment by Taewan-P** [comment]
@vonhyd Does this still occur on the latest version, v0.5.0?

**Comment by vonhyd** [comment]
flickering is fixed but the context menu still moves up when you scroll in the text box while selecting text

**Comment by Taewan-P** [comment]
I think that is intended since the selected text moves up when you scroll. It is kinda weird though.. I think when the selected part is not shown on the screen due to scrolling, the context menu should not appear.

This is most likely a Jetpack compose Library issue, not the app's issue. So this should be reported to Google Issue tracker.

**Comment by vonhyd** [comment]
Thank you for all your hard work!
