### ISSUE TITLE
Issue with Claude AI

### ISSUE THREAD

**Issue by Jonny-T-cyber** [Taewan-P/gpt_mobile#70]
Unable to run prompt with Claude AI.
With any model I choose I always get the error visible in the attached screenshot.

![Screenshot_20241012-121720_GPTMobile.jpg](https://github.com/user-attachments/assets/b073e4bc-78f7-468c-b8a7-597320127674)

**Comment by Taewan-P** [comment]
Hi! This is not an app specific bug.
This occurs because you do not have any credit on your Anthropic account.
In order to use Anthropic APIs, you need to charge a certain amount of credit. Then the system uses your credit for the API calls you make.

**Comment by Taewan-P** [comment]
Yes. because it's a nonfree API
