### ISSUE TITLE
latestMessageIndex always 0

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Taewan-P/gpt_mobile#72]
**Describe the bug**
in `ChatScreen.kt`. `latestMessageIndex` is always 0. which caused a `java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2` at `.horizontalScroll(chatBubbleScrollStates[(key - 1) / 2])` in line 191 if chat more than 3 turn

**To Reproduce**
1. chat more than 3 turn (6 messages in total)
2. restart app
3. enter chat

**Expected behavior**
no crash

**Screenshots or Screen Recording**
no

**Additional context**
it didt crash when turn < 3 is because `val chatBubbleScrollStates = rememberSaveable(saver = multiScrollStateSaver) { MutableList(latestMessageIndex + 2) { ScrollState(0) } }` have 0+2 ScrollState initialized by default

`latestMessageIndex` been updated to correct value after recomposition. but crash happens before it

**Comment by Taewan-P** [comment]
This will be include in the next release, coming this week.
