### ISSUE TITLE
Setting won't get saved

### ISSUE THREAD

**Issue by tristan-k** [Taewan-P/gpt_mobile#81]
**Describe the bug**

After entering the settings in the startup screen and restarting the app, the settings are lost.

Here's a screen recording of the bug.

https://github.com/user-attachments/assets/2fce437b-fa21-4ad2-8c69-73b5f54da9c2

**Comment by Taewan-P** [comment]
@tristan-k Hi! Thanks for the report! I will look into it.
Before digging further, what app version are you using?

**Comment by tristan-k** [comment]
Version 0.5.1 from the Google Play Store.

**Comment by Taewan-P** [comment]
Hi. just fixed the issue. It will be updated in the next release.

**Comment by tristan-k** [comment]
Great thanks! On other thing not related to the issue. I would appreciate if you could add an option to select more than one ollama sever. See this [github issue](https://github.com/JHubi1/ollama-app/issues/48) from another android app with a similiar goal.

**Comment by Taewan-P** [comment]
I think that would be related to #62 & #67.
