### ISSUE TITLE
Feature request: Offer "OpenAI DALL·E"

### ISSUE THREAD

**Issue by PanderMusubi** [Taewan-P/gpt_mobile#96]
Support image generation with OpenAI DALL·E.

The settings for this are based on OpenAI settings but the API used is https://platform.openai.com/docs/guides/images/usage

User needs to provide the same or siminar API key as for OpenAI. The API call will be made to `dall-e-3` (but the user can also select other models such as `dall-e-2`) with user settings for `n` (default `1`) `size` (default `1024x1024`) and `quality` (default `normal`). 

Temperature, nucleus and system prompt are not needed. Note also the maximum string length which differs per model.

The result will be one or more URLs. No URL for errors, but showing the error message of course. A setting can be added that the URLs are also automatically opened in the device's default web browser (default no).

Alternatively, the images are shown in the app and saved in the cache of the app. This would be an advantage over only the URL that expires. Note, showing the URLs for sharing with others (for as long as they last) is still practical. Sharing images from the cache would be another advantage. 

Implementing this would help e.g. on-the-go (mobile) brainstorming and concept development.

**Comment by Taewan-P** [comment]
Issue is only for bug report. Use discussions for any other requests.
This app is a chat based app, so the current app architecture and its UI flow cannot support image generation.
