### ISSUE TITLE
Unable to use ChatGPT

### ISSUE THREAD

**Issue by Sam-Krupakar73** [Taewan-P/gpt_mobile#98]
**Describe the bug**

**To Reproduce**
1. Go to GPT Mobile app
2. Click on + New chat
3. Scroll down to 
4. See error : The model `gpt-4-turbo` does not exist or you do not have access to it.

**Expected behavior**

**Screenshots or Screen Recording**

**Additional context**

**Comment by Taewan-P** [comment]
I just checked and there is no problem with the app. Did you provide your API keys and charged a small amount of credit?

**Comment by cust0muser** [comment]
I have the same problem. I can't use ChatGPT. I'm using the free version of chatgpt.

**Comment by Taewan-P** [comment]
It's not about the free version or subscription version. It's about your API key and the remaining credit in your account.

**Comment by cust0muser** [comment]
> .

Thanks for the quick reply. I just tried it with claude, but I get an error message here too. It seems that in both models you have to top up money first in order to be able to use the API.

**Comment by Taewan-P** [comment]
Yes that is correct. You need to charge credits first before using the API keys.

If you have any more questions, feel free to ask via Discussions.
